# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2434c542069a08cc6c14e4a14541d6376c58f8c8cc300b061cf942568611092f61d612e544b065346d70900482d0f95426e36eaea5b62391aab3f04e27a4c13e

test:
  secret_key_base: c92696de8a6e57ef9159ba92d26f801ef765d546f68baeba2538e9bc396dd81d557cd1f34abe006c43023e17a3a56f4a28a04d3e37baaaee98e454cee1ff77ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
